name: Release package

on:
  release:
    types:
      - published
env:
  package: ${{ format('{0}-{1}', github.event.repository.name, github.event.release.tag_name) }}

permissions:
  contents: write

jobs:
  upload-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          path: ${{ env.package }}
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Build
        run: |
          cd "$package"
          npm ci
          npm run build
          cd ../
          zip -r "${package}.zip" "${package}/" \
            -x "${package}/.git/*" \
            -x "${package}/node_modules/*"
      - name: Upload asset
        env:
          token: ${{ github.token }}
          url: ${{ github.event.release.upload_url }}
        run: |
          upload_url="${url%%\{*}?name=${package}.zip"
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${token}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/zip" \
          "$upload_url" \
          --data-binary "@${package}.zip"
